### PR TITLE
fix: list dependencies by invoking the interpreter on a binary

### LINKED ISSUE #3: `ldd` potentially runs a binary outside the sandbox
Similar to https://github.com/Zouuup/landrun/issues/23

To quote the `ldd` manpages:
> Be aware that in some circumstances (e.g., where the program specifies an ELF interpreter other than ld-linux.so), some versions of ldd may attempt to obtain the dependency information by attempting to directly execute the program, which may lead to the execution of whatever code is defined in the program's ELF interpreter, and perhaps to execution of the program itself.

### PR DESCRIPTION
**Pull request by lavafroth**
Fixes #3

### Changes

- Creates a new module called ldd
- Parses the target binary's ELF headers
- Extracts the interpreter from the `.interp` section
- Calls the interpreter on the binary with the `--list` flag to query shared object dependencies
- Recursively parses the entire dependency tree

### CODE REVIEW

File: src/main.rs [hunk 1]
```diff
@@ -149,13 +150,11 @@ fn main() -> Result<()> {
 
     // Add library dependencies if requested
     if cli.ldd {
-        match exec::get_library_dependencies(&binary_path_str) {
```
Comment (creslinux) [inline src/main.rs:152]: Lets remove this from the exec module if no longer required

**Review by creslinux — COMMENTED** [review]
This looks great - its definitely better then using the systems linker, thank you.  If can remove the now defunct fn in exec we can merge

I'll update the docu/site this week to reflect the change to the helper.

File: src/main.rs (hunk 1 above)
Comment (lavafroth) [reply src/main.rs:152]: Done

**Review by creslinux — APPROVED** [review]
LGTM - thank you for the change
